# Generated by Django 4.0 on 2022-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fram_dt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('em', models.EmailField(max_length=254)),
                ('gn', models.CharField(max_length=10)),
                ('rg', models.CharField(max_length=50)),
                ('st', models.CharField(max_length=50)),
                ('sb', models.CharField(max_length=50)),
                ('nf', models.CharField(max_length=50)),
            ],
        ),
    ]
