# Generated by Django 4.0.4 on 2022-04-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fram_dt',
            old_name='em',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='fn',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='gn',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='ln',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='nf',
            new_name='nextcrop',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='rg',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='sb',
            new_name='stype',
        ),
        migrations.RenameField(
            model_name='fram_dt',
            old_name='st',
            new_name='subtp',
        ),
    ]
